
package pl.edu.agh.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VendorControllerService", targetNamespace = "http://api.soa.agh.edu.pl/", wsdlLocation = "http://localhost:8080/SOA-1/VendorController?wsdl")
public class VendorControllerService
    extends Service
{

    private final static URL VENDORCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException VENDORCONTROLLERSERVICE_EXCEPTION;
    private final static QName VENDORCONTROLLERSERVICE_QNAME = new QName("http://api.soa.agh.edu.pl/", "VendorControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOA-1/VendorController?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VENDORCONTROLLERSERVICE_WSDL_LOCATION = url;
        VENDORCONTROLLERSERVICE_EXCEPTION = e;
    }

    public VendorControllerService() {
        super(__getWsdlLocation(), VENDORCONTROLLERSERVICE_QNAME);
    }

    public VendorControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VENDORCONTROLLERSERVICE_QNAME, features);
    }

    public VendorControllerService(URL wsdlLocation) {
        super(wsdlLocation, VENDORCONTROLLERSERVICE_QNAME);
    }

    public VendorControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VENDORCONTROLLERSERVICE_QNAME, features);
    }

    public VendorControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VendorControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VendorController
     */
    @WebEndpoint(name = "VendorControllerPort")
    public VendorController getVendorControllerPort() {
        return super.getPort(new QName("http://api.soa.agh.edu.pl/", "VendorControllerPort"), VendorController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VendorController
     */
    @WebEndpoint(name = "VendorControllerPort")
    public VendorController getVendorControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.soa.agh.edu.pl/", "VendorControllerPort"), VendorController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VENDORCONTROLLERSERVICE_EXCEPTION!= null) {
            throw VENDORCONTROLLERSERVICE_EXCEPTION;
        }
        return VENDORCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
